### ISSUE TITLE
a Readme.txt shall be provided for ./FINT_CH_Process 

### ISSUE THREAD

**Issue by Rdataflow** [HAFL-WWI/pyFINT#1]
a Readme.txt shall be provided for ./FINT_CH_Process in order to understand how to launch the FINT_CH_Process
- [x] describing the prerequisits 
  - [x] install the required python packages `requirements.txt` (to be provided)
  - [x] setup a PostGIS db with db, user, grant, table_schema, etc.
  - [x] configure the config files
  - [x] ... what else ?
- [x] explaining how to start the FINT_CH_Process
  - [x] setup env vars PYFINT_HOME, FINTCH_HOME, FINTCH_CONFIG_HOME, ...
  - [x] run the process via `python ./FINT_CH_Process/Processing/fintch_processing_process_kantone.py`

**Comment by ChSchaller** [comment]
With the latest commit (f31a523ad21fc45c2b4480a1bd75263d99201848) a readme.md and requirements.txt for the FINT-CH process has been added. The readme should cover the necessary steps and configurations needed to run the script. Creating a PostGIS database, schema, and user are standard tasks described in enough detain in the PostgreSQL/PostGIS documentations and are therefore not covered in detail. The creation of the tables is automated by the script.
